# Generated by Django 6.0.3 on 2026-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livros",
            options={
                "ordering": ["titulo"],
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
            },
        ),
        migrations.AlterField(
            model_name="livros",
            name="co_autor",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="livros",
            name="data_devolucao",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="livros",
            name="data_emprestimo",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="livros",
            name="nome_emprestado",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="livros",
            name="tempo_duracao",
            field=models.DateField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name="livros",
            unique_together={("titulo", "autor", "co_autor")},
        ),
    ]
