# Generated by Django 6.0.3 on 2026-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0003_alter_livros_data_cadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="data_emprestimo",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
