# Generated by Django 6.0.3 on 2026-03-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0004_alter_livros_data_emprestimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="data_devolucao",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
