# Generated by Django 6.0.3 on 2026-03-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0005_alter_livros_data_devolucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="tempo_duracao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
