# Generated by Django 6.0.3 on 2026-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0006_alter_livros_tempo_duracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
