# Generated by Django 6.0.3 on 2026-03-18 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0007_alter_livros_data_cadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 18, 16, 33, 41, 406339)
            ),
        ),
    ]
