# Generated by Django 6.0.3 on 2026-03-21 12:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0011_alter_livros_data_cadastro"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateField(default=datetime.date(2026, 3, 21)),
        ),
        migrations.AddField(
            model_name="livros",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="livro.categoria",
            ),
            preserve_default=False,
        ),
    ]
