# Generated by Django 6.0.3 on 2026-03-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0012_categoria_alter_livros_data_cadastro_and_more"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="livros",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuario.usuarios",
            ),
            preserve_default=False,
        ),
    ]
