# Generated by Django 6.0.3 on 2026-03-24 21:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0013_alter_categoria_options_livros_usuario"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuario.usuarios",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateField(default=datetime.date(2026, 3, 24)),
        ),
    ]
