# Generated by Django 6.0.3 on 2026-03-25 15:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0014_categoria_usuario_alter_livros_data_cadastro"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livros",
            name="data_devolucao",
        ),
        migrations.RemoveField(
            model_name="livros",
            name="data_emprestimo",
        ),
        migrations.RemoveField(
            model_name="livros",
            name="nome_emprestado",
        ),
        migrations.RemoveField(
            model_name="livros",
            name="tempo_duracao",
        ),
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateField(default=datetime.date(2026, 3, 25)),
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_emprestado", models.CharField(blank=True, max_length=50)),
                ("data_emprestimo", models.DateTimeField(blank=True, null=True)),
                ("data_devolucao", models.DateTimeField(blank=True, null=True)),
                ("tempo_duracao", models.DateField(blank=True, null=True)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="livro.livros",
                    ),
                ),
            ],
        ),
    ]
