# Generated by Django 6.0.3 on 2026-03-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0015_remove_livros_data_devolucao_and_more"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="nome_emprestado_anonimo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="nome_emprestado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="usuario.usuarios"
            ),
        ),
    ]
