# Generated by Django 6.0.3 on 2026-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0016_emprestimo_nome_emprestado_anonimo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateField(blank=True, null=True),
        ),
    ]
