# Generated by Django 6.0.3 on 2026-03-25 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0017_alter_emprestimo_data_devolucao_and_more"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emprestimo",
            name="tempo_duracao",
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="nome_emprestado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuario.usuarios",
            ),
        ),
    ]
