# Generated by Django 6.0.3 on 2026-03-28 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0018_remove_emprestimo_tempo_duracao_and_more"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprestimo",
            name="avaliacao",
            field=models.CharField(
                choices=[("P", "Péssimo"), ("R", "Ruim"), ("B", "Bom"), ("O", "Otimo")],
                default=1,
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateField(default=datetime.date(2026, 3, 28)),
        ),
        migrations.AlterUniqueTogether(
            name="categoria",
            unique_together={("name", "descricao", "usuario")},
        ),
    ]
