# Generated by Django 6.0.3 on 2026-03-28 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0019_emprestimo_avaliacao_alter_livros_data_cadastro_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 28, 18, 42, 46, 104489)
            ),
        ),
    ]
