# Generated by Django 6.0.3 on 2026-03-28 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0020_alter_emprestimo_data_emprestimo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="data_devolucao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 28, 18, 45, 8, 53374)
            ),
        ),
    ]
