# Generated by Django 6.0.3 on 2026-03-29 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livro", "0021_alter_emprestimo_data_devolucao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emprestimo",
            name="avaliacao",
            field=models.CharField(
                blank=True,
                choices=[("P", "Péssimo"), ("R", "Ruim"), ("B", "Bom"), ("O", "Otimo")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emprestimo",
            name="data_emprestimo",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 29, 18, 55, 33, 754967)
            ),
        ),
        migrations.AlterField(
            model_name="livros",
            name="data_cadastro",
            field=models.DateField(default=datetime.date(2026, 3, 29)),
        ),
    ]
