# Generated by Django 6.0.3 on 2026-04-27 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0024_livros_img_alter_emprestimo_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 27, 16, 2, 19, 866549)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2026, 4, 27)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='img',
            field=models.ImageField(default=1, upload_to='capa_livro'),
            preserve_default=False,
        ),
    ]
